### ISSUE TITLE
Какие есть методы Кинематической калибровки?

### ISSUE THREAD

**Issue by Robotics010** [Robotics010/ar600e-default#11]
Необходимо провести обзор методов Кинематической калибровки. Насколько я понимаю, есть open-loop и close-loop методы - с внешней системой измерения и без неё, соответственно.

**Comment by VladimirAlD** [comment]
Предварительный вариант обзора, пока на английском языке
[Calibration.docx](https://github.com/Robotics010/ar600e-default/files/2413894/Calibration.docx)

**Comment by VladimirAlD** [comment]
[Методы_управления_робототехническими_приложениями.pdf](https://github.com/Robotics010/ar600e-default/files/2413902/2094.pdf)
Вот неплохой материал, из ИТМО

**Comment by Robotics010** [comment]
Проверят не будем, ввиду экономии времени.
