### ISSUE TITLE
Есть ли функционал стереозрения?

### ISSUE THREAD

**Issue by Robotics010** [Robotics010/ar600e-default#12]
Необходимо реализовать модуль стереозрения в ROS.

**Comment by Robotics010** [comment]
@Curucum нужно сделать модуль в ROS, который бы на вход получал два изображения, а на выходе давал облако точек. Но нужно посмотреть как это правильно реализовать.
Может быть более правильно сделать модуль, который бы и собирал данные с камер и рассчитывал карту глубин, потому что паре камер (стереопаре) нужна калибровка. А значит эту калибровку нужно производить и сохранять в файле, а калибровочный файл использовать при построении облака точек.

**Comment by Robotics010** [comment]
Как вообще в ROS правильно реализуется работа с камерами? Какова архитектура программ при обработке изображений в ROS?

**Comment by Curucum** [comment]
http://wiki.ros.org/camera_calibration/Tutorials/StereoCalibration Пробовал вот это, не получилось, пишет, что не подходит система

**Comment by Curucum** [comment]
https://www.youtube.com/watch?v=-omqbmmUX1E вот это также пробовал, не подходит, возможно нужно запустить из определенного места

**Comment by Robotics010** [comment]
На данный момент направление работы временно отменено
