### ISSUE TITLE
Какой способ ОК используется в MoveIt! у нас?

### ISSUE THREAD

**Issue by Robotics010** [Robotics010/ar600e-default#14]
Какой способ решения задачи обратной кинематики (ОК) используется по умолчанию в MoveIt! у нас?

**Comment by VladimirAlD** [comment]
При решении задач кинематики использовали стандартный решатель библиотеки [Orocos_KDL](http://www.orocos.org/kdl) нооо он не работает если <6DOFs. 
Альтернива, для <6DOF, IKFast и Trac-IK.
Orocos-KDL и Track-IK – числовые, IKFast – аналитический.
ссылки на код:
[Orocos_KDL](https://github.com/orocos/orocos_kinematics_dynamics)
[Track-IK](https://bitbucket.org/traclabs/trac_ik/overview)
IKFast – //

**Comment by Robotics010** [comment]
В уроке Generate [IKFast Plugin Tutorial](http://docs.ros.org/indigo/api/moveit_tutorials/html/doc/ikfast_tutorial.html) указано, что

> The IKFast plugin should function identically to the default KDL IK Solver, but with greatly increased performance.

**Comment by Robotics010** [comment]
У нас в нашем kinematics.yaml (ar600e-default/moveit_arbot/config/kinematics.yaml) явно указан текущий решатель:

> kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin

**Comment by Robotics010** [comment]
В [Kinematics Configuration Tutorial](http://docs.ros.org/indigo/api/moveit_tutorials/html/doc/pr2_tutorials/kinematics/src/doc/kinematics_configuration.html) явно сказано что

> The KDL Kinematics Plugin is the default kinematics plugin currently used by MoveIt!

Тут же сказано, что

> The KDL kinematics plugin wraps around the numerical inverse kinematics solver provided by the Orocos KDL package.
Т.е. решатель построен на базе численного метода

**Comment by Robotics010** [comment]
Сам решатель в ROS описан здесь - [orocos_kdl](http://wiki.ros.org/orocos_kdl) (ранее здесь - [kdl](http://wiki.ros.org/kdl))

**Comment by Robotics010** [comment]
Судя по описанию [KDL::ChainIkSolverPos Class Reference](http://docs.ros.org/indigo/api/orocos_kdl/html/classKDL_1_1ChainIkSolverPos.html) для решения ОК используется

- Solver for the inverse position kinematics that uses Levenberg-Marquardt. [Ссылка](http://docs.ros.org/indigo/api/orocos_kdl/html/classKDL_1_1ChainIkSolverPos__LMA.html)

или

- Implementation of a general inverse position kinematics algorithm based on Newton-Raphson iterations. [Ссылка](http://docs.ros.org/indigo/api/orocos_kdl/html/classKDL_1_1ChainIkSolverPos__NR.html)

**Comment by Robotics010** [comment]
Исходные файлы решателей
[kdl_kinematics_plugin.cpp](https://github.com/ros-planning/moveit/blob/indigo-devel/moveit_kinematics/kdl_kinematics_plugin/src/kdl_kinematics_plugin.cpp)
[kdl_kinematics_plugin.h](https://github.com/ros-planning/moveit/blob/indigo-devel/moveit_kinematics/kdl_kinematics_plugin/include/moveit/kdl_kinematics_plugin/kdl_kinematics_plugin.h)

**Comment by Robotics010** [comment]
https://www.mi.ams.eng.osaka-u.ac.jp/member/sugihara/pub/ichr09.pdf

**Comment by Robotics010** [comment]
http://people.duke.edu/~hpgavin/ce281/lm.pdf здесь подробно про сам метод (Анжела)

**Comment by Robotics010** [comment]
В книге Bertsekas, Dimitri P. Nonlinear Programming. Belmont, MA: Athena Scientific, 1999 есть упоминание о Levenberg-Marquardt method на странице 91

**Comment by Robotics010** [comment]
В книге Nocedal, Jorge, and Stephen Wright. Numerical Optimization. New York, NY: Springer, 2006 есть целый раздел, посвященный  The Levenberg–Marquardt Method и еще раздел, посвященный его реализации

**Comment by Robotics010** [comment]
Newton-Raphson - Engineering_Mathematics_4th_ed_-_J_Bird - с. 123 по оглавлению (Анжела)

**Comment by Robotics010** [comment]
Выполняю уроки из [Indigo MoveIt! Tutorials](http://docs.ros.org/indigo/api/moveit_tutorials/html/index.html), чтобы разобраться какой из методов выше используется по умолчанию.

**Comment by Robotics010** [comment]
http://docs.ros.org/indigo/api/moveit_tutorials/html/doc/ros_visualization/visualization_tutorial.html
https://github.com/ros-planning/moveit_tutorials/issues/74

I attempted Setup Assistant Tutorial followed by the RViz Plugin Tutorial
No interactive marker was displayed in RViz and the following error was logged to terminal:

[ INFO] [1508344563.774111009]: Loading robot model 'pr2'...
[ERROR] [1508344563.785211118]: Group 'right_arm' is not a chain
[ERROR] [1508344563.785262245]: Kinematics solver of type 'kdl_kinematics_plugin/KDLKinematicsPlugin' could not be initialized for group 'right_arm'
[ERROR] [1508344563.785979936]: Kinematics solver could not be instantiated for joint group right_arm.
[ INFO] [1508344563.799430428]: Loading robot model 'pr2'...
[ERROR] [1508344563.810831186]: Group 'left_arm' is not a chain
[ERROR] [1508344563.810856901]: Kinematics solver of type 'kdl_kinematics_plugin/KDLKinematicsPlugin' could not be initialized for group 'left_arm'
[ERROR] [1508344563.811354335]: Kinematics solver could not be instantiated for joint group left_arm.

I solved this by modifying MoveIt Setup Assistant Planning Groups for right_arm (and left_arm) to be a chain instead of joints.

right_arm > Chain > r_shoulder_pan_link -> r_wrist_roll_link
right_gripper > Links > r_gripper_palm_link -> r_gripper_tool_frame
left_arm > Chain > l_shoulder_pan_link -> l_wrist_roll_link
left_gripper > Links > l_gripper_palm_link -> l_gripper_tool_frame

**Comment by Robotics010** [comment]
Довольно подробное и понятное объяснение по IK Solvers в ROS и MoveIt! "Performance optimization and implementation of evolutionary inverse kinematics in ROS" https://tams.informatik.uni-hamburg.de/publications/2017/MSc_Philipp_Ruppel.pdf

**Comment by Robotics010** [comment]
Вопрос аналогичный нашему, но ответа по реализованному алгоритму нет - http://www.orocos.org/forum/orocos/orocos-users/kdl-algorithm-details

**Comment by Robotics010** [comment]
> При решении задач кинематики использовали стандартный решатель библиотеки [Orocos_KDL](http://www.orocos.org/kdl) нооо он не работает если <6DOFs.

Да, действительно. Тогда почему [у нас в качестве решателя используется](https://github.com/Robotics010/ar600e-default/blob/master/moveit_arbot/config/kinematics.yaml)
`kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin`
?

**Comment by Robotics010** [comment]
Итого, по используется KDLKinematicsPlugin - решатель обратной позиционной задачи кинематики на базе Orocos_KDL. Это численный метод на базе матриц Якоби. В документации к KDLKinematicsPlugin 
 было описано, что используется либо Levenberg–Marquardt либо Newton-Raphson.
Эти методы не рассчитаны только для манипуляторов с 6 или более степенями свободы. В нашем роботе сейчас руки-манипуляторы 5 DOF.

Нужно уточнить чем вызваны такие ограничения, во что это выливается.
Рекомендуется использовать вместо KDLKinematicsPlugin  -  [MoveIt! ikfast plugin](http://docs.ros.org/indigo/api/moveit_tutorials/html/doc/ikfast_tutorial.html).
Или можно сделать свой решатель и импортировать его в ROS. Есть инструкции по этому поводу.
