### ISSUE TITLE
Обратная кинематика в Matlab

### ISSUE THREAD

**Issue by VladimirAlD** [Robotics010/ar600e-default#26]
Если проверять углы, полученные с помощью SerialLink.ikcon (Inverse kinematics by optimization with joint limits), с помощью прямой кинематики то решения не сходятся. 
Если поочередно нажимать forward/inverse, то он приходит в вертикальное положение
![screenshot_1](https://user-images.githubusercontent.com/38034211/47841288-2a714a00-ddca-11e8-89b4-ff2ed8c65311.png)

[Файлы для запуска](https://github.com/Robotics010/ar600e-default/tree/master/Matlab_Kinematic) invKinematic.m | invKinematic.fig (GUI)
 
Matlab 2016a
[Robotic Toolbox 10.3](http://petercorke.com/wordpress/toolboxes/robotics-toolbox)

**Comment by Robotics010** [comment]
Вопрос возник в процессе решения https://github.com/Robotics010/ar600e-default/issues/15

**Comment by VladimirAlD** [comment]
![screenshot_5](https://user-images.githubusercontent.com/38034211/48124584-bc2afc80-e28d-11e8-8c5b-e1173c21f481.png)
Добавил звено, но ничего не поменялось
![screenshot_1](https://user-images.githubusercontent.com/38034211/48124588-c0571a00-e28d-11e8-99f3-de10e0f3b26e.png)
Матрица T, получаемая при .fkine[pi/4 0 -pi/6 0 0 0], значения XYZ=[0.48896 0.045608 -0.20178]
![screenshot_2](https://user-images.githubusercontent.com/38034211/48124589-c0571a00-e28d-11e8-9350-7352faf06c37.png)
Матрица T_des, получаемая функцией transl([PX PY PZ]), где PX, PY, PZ желаемое положение
![screenshot_3](https://user-images.githubusercontent.com/38034211/48124590-c0efb080-e28d-11e8-889c-f8ff77e95761.png)
Результат ikcon(T_des)
![screenshot_4](https://user-images.githubusercontent.com/38034211/48124592-c0efb080-e28d-11e8-972f-3a69a1d45529.png)
Результат .ikcon(T)
Надо добиться соответствия T_des матрице T...

**Comment by Robotics010** [comment]
Отложили до "лучших времен"
