### ISSUE TITLE
Ошибка при запуске moveit_arbot

### ISSUE THREAD

**Issue by Robotics010** [Robotics010/ar600e-default#29]
Пытаюсь запустить демонстрацию moveit_arbot
`roslaunch moveit_arbot demo.launch`
Но завершается с ошибкой
`[rviz_rosuser_Latitude_E5420_2704_4200105157973114964-5] process has died [pid 2737, exit code -11, cmd /opt/ros/indigo/lib/rviz/rviz -d /home/rosuser/catkin_ws/src/ar600e-default/moveit_arbot/launch/moveit.rviz __name:=rviz_rosuser_Latitude_E5420_2704_4200105157973114964 __log:=/home/rosuser/.ros/log/57f79fd6-ec81-11e8-8fbf-a088b46f4ff4/rviz_rosuser_Latitude_E5420_2704_4200105157973114964-5.log].
log file: /home/rosuser/.ros/log/57f79fd6-ec81-11e8-8fbf-a088b46f4ff4/rviz_rosuser_Latitude_E5420_2704_4200105157973114964-5*.log`

![screenshot from 2018-11-20 08 19 51](https://user-images.githubusercontent.com/16175093/48753019-2d5eac80-ec9d-11e8-9bc5-87413ac5aee5.png)

Похоже проблема в том, что пути в URDF файле прописаны абсолютные, а не относительные.
![screenshot from 2018-11-20 08 21 14](https://user-images.githubusercontent.com/16175093/48753041-4bc4a800-ec9d-11e8-8cdf-e855e5c4a430.png)

Пример тега из ARbot_v4.urdf:
`<mesh filename="file:///home/vladimir/catkin_ws/src/arbot_model_pkg/meshes/STL/taz.stl" scale="0.001 0.001 0.001"/>`

**Comment by Robotics010** [comment]
Команда
`roscd arbot_model_pkg`
выполняется успешно

**Comment by Robotics010** [comment]
Заменил в ARbot_v2.urdf, теперь пути выглядят:
`<mesh filename="arbot_model_pkg://meshes/STL/taz.stl" scale="0.001 0.001 0.001"/>`
Но теперь ошибка:
`[ WARN] [1542776187.369269592]: OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource arbot_model_pkg://meshes/STL/tors.stl in resource group Autodetect or any other group. in ResourceGroupManager::openResource at /build/buildd/ogre-1.8-1.8.1+dfsg/OgreMain/src/OgreResourceGroupManager.cpp (line 756)
[ERROR] [1542776187.369346775]: Could not load model 'arbot_model_pkg://meshes/STL/tors.stl' for link 'tors': OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource arbot_model_pkg://meshes/STL/tors.stl in resource group Autodetect or any other group. in ResourceGroupManager::openResource at /build/buildd/ogre-1.8-1.8.1+dfsg/OgreMain/src/OgreResourceGroupManager.cpp (line 756)`
![screenshot from 2018-11-21 07 59 52](https://user-images.githubusercontent.com/16175093/48819911-7416da00-ed63-11e8-98b0-bc0102fb0214.png)

**Comment by Robotics010** [comment]
Если заменить на вот такое:
<mesh filename="package://meshes/STL/taz.stl" scale="0.001 0.001 0.001"/>
То проблема аналогичная
![screenshot from 2018-11-21 08 02 03](https://user-images.githubusercontent.com/16175093/48819988-d7087100-ed63-11e8-94e5-fbfea032a70c.png)

**Comment by VladimirAlD** [comment]
Путь должен быть
<mesh filename="package://arbot_model_pkg/meshes/STL/taz.stl" scale="0.001 0.001 0.001"/>

**Comment by Robotics010** [comment]
Если у меня путь
`rosuser@rosuser-Latitude-E5420:~$ roscd arbot_model_pkg
rosuser@rosuser-Latitude-E5420:~/catkin_ws/src/ar600e-default/arbot_model_pkg$ `
То ты предлагаешь в моем URDF файле заменить на что?
Как должно выглядеть пример тега из ARbot_v2.urdf?
`<mesh filename="file:///home/vladimir/catkin_ws/src/arbot_model_pkg/meshes/STL/taz.stl" scale="0.001 0.001 0.001"/>`

**Comment by VladimirAlD** [comment]
С телефона неудобно писать) как выделять так код? Просто без выделения он не отображается из за < />
Выше написал, как они у меня

**Comment by Robotics010** [comment]
Нет, я понимаю как заменить у меня на мой путь к файлу. Но это решение проблемы только для моего случая.
Я же настаиваю на том, что решить проблему нужно так, что у тех, кто скачивает его себе, тоже работало. Т.е. нужно вставить относительные пути. Как это сделать?

**Comment by VladimirAlD** [comment]
Это 
mesh filename="file:///home/vladimir/catkin_ws/src/arbot_model_pkg/meshes/STL/taz.stl" scale="0.001 0.001 0.001"/>
должно выглядеть так
mesh filename="package://arbot_model_pkg/meshes/STL/taz.stl" scale="0.001 0.001 0.001"/>
Это уже относительный получается, имя пользователя не присутствует

**Comment by VladimirAlD** [comment]
Добрый

**Comment by Robotics010** [comment]
Вот это уже другое дело. Работает.
![screenshot from 2018-11-21 08 18 57](https://user-images.githubusercontent.com/16175093/48820487-25b70a80-ed66-11e8-96ee-640b33fdc1be.png)

**Comment by Robotics010** [comment]
Внес изменения d594ff0950526ea2b770dcb903e611f9fdfa3cf1
